name: Minhaz's Blog
research_name: Minhaz's Experiments
title: Minhaz's Blog
small_description: "Hack your way out!"
description: "I work full time as a Software Engineer at Google. Time to time I come across problems I don't find solutions to on web and I try to pen it down here. My area of expertise are distributed systems, android, android camera, emerging markets, applied ML and computational photography. I am sometimes identified as mebjas or minhazav."
avatar: https://blog.minhazav.dev/images/rsz_self_1_1.jpg
logo: https://blog.minhazav.dev/images/rsz_self_1_1.jpg
github: mebjas
email: minhazav@gmail.com
author:
  twitter: minhazav
  picture: https://blog.minhazav.dev/images/rsz_self_1_1.jpg
twitter:
  username: minhazav
  card: summary
social:
  name: A V Minhaz
  links:
    - https://twitter.com/minhazav
    - https://www.instagram.com/mebjas
    - https://www.linkedin.com/in/minhazav
    - https://github.com/mebjas
    - https://500px.com/mebjas

copyright_year: 2019
copyright_owner: minhazav.dev
category_dir: category
url: "https://blog.minhazav.dev"
# repository: "mebjas/mebjas.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Includes an icon in the footer for each username you enter
footer-links:
  email: minhazav@gmail.com
  facebook:
  github: mebjas
  github_full: "https://github.com/mebjas"
  instagram: mebjas
  linkedin: "https://www.linkedin.com/in/minhazav"
  twitter: minhazav
  stackoverflow: users/2614250/mebjas

# Outputting
permalink: /:title/
timezone: Etc/UTC

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
highlighter: rouge
strict_front_matter: true

# Collections
collections:
  google_work:
    output: true
    order:
      - title
      - date

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  blanklines: true
  clippings: all
  comments: all

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - staticman.yml

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "google_work"
    values:
      layout: "post"

category_descriptions:
  - { name: "distributed-systems", description: "" }
  - { name: "hackathon", description: "" }
  - { name: "key-value-store", description: "" }
  - { name: "nodejs", description: "" }
  - { name: "graphics", description: "" }
  - { name: "html-canvas", description: "" }
  - { name: "javascript", description: "" }
  - { name: "python", description: "" }
  - { name: "dotnet", description: "" }
  - { name: "php", description: "" }
  - { name: "apache", description: "" }
  - { name: "mathematics", description: "" }
  - { name: "csrf", description: "" }
  - { name: "open-source", description: "" }
  - { name: "owasp", description: "" }
  - { name: "security", description: "" }
  - { name: "web-security", description: "" }
  - { name: "compression", description: "" }
  - { name: "encoding", description: "" }
  - { name: "decoding", description: "" }
  - { name: "bits-manipulation", description: "" }
  - { name: "architecture", description: "" }
  - { name: "system-design", description: "" }
  - { name: "azure", description: "" }
  - { name: "azure-storage-blob", description: "" }
  - { name: "azure-storage-table", description: "" }
  - { name: "machine-learning", description: "" }
  - { name: "microsoft", description: "" }
  - { name: "cloud", description: "" }
  - { name: "interview", description: "" }
  - { name: "interview-tips", description: "" }
  - { name: "android", description: "" }
  - { name: "android-11", description: "" }
  - { name: "android-R", description: "" }
  - { name: "android", description: "" }
  - { name: "hal", description: "" }
  - { name: "image-processing", description: "" }
  - { name: "hardware", description: "" }
  - { name: "privacy", description: "" }
  - { name: "isp", description: "" }
  - { name: "dsp", description: "" }
  - { name: "lens", description: "" }
  - { name: "sensor", description: "" }
  - { name: "computational-photograhpy", description: "" }
  - { name: "android-camera", description: "" }
  - { name: "camera", description: "" }
  - { name: "linux", description: "" }
  - { name: "memory", description: "" }
  - { name: "shared-memory", description: "" }
  - { name: "mmap", description: "" }
  - { name: "munmap", description: "" }
  - { name: "malloc", description: "" }

photography_data_path: "photography/assets/"